[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'meson >= 1.1.0', 'numpy']

[project]
name = "spharm_fortran_reference"

license = {file = "LICENSE"}

description = "The fortran reference for spectralkernel_rs"
authors = [
    {name = "atmos"},
]
requires-python = ">=3.10"
readme = "README.md"
classifiers = [
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Scientific/Engineering',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: Unix',
]
dependencies = [
    'numpy >= 1.24.3',
    'intel-fortran-rt',
    'dpcpp-cpp-rt',
    'wrapt'
]
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/easyatmos/spectralkernel_rs"
documentation = "https://github.com/easyatmos/spectralkernel_rs"
source = "https://github.com/easyatmos/spectralkernel_rs"
download = "https://pypi.org/project/spectralkernel_rs/#files"
tracker = "https://github.com/easyatmos/spectralkernel_rs/issues"

[tool.setuptools.dynamic]
version = {attr = "spharm_fortran_reference.__version__"}

[tool.setuptools_scm]

[tool.setuptools.packages.find]
where = ["./"]
