"""Render a SPHEREPACK-style lumpy sphere figure.

This reproduces the idea behind the SPHEREPACK 3.2 docs image generated by
VISGAU, using NumPy/SciPy for the scalar harmonic and Matplotlib for rendering.

Run in root dir, and fig is in the `readme`.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
from matplotlib.colors import LightSource, Normalize
from scipy.special import sph_harm_y


def gaussian_colatitudes(nlat: int) -> np.ndarray:
    """Return north-to-south Gaussian colatitudes."""
    nodes, _ = np.polynomial.legendre.leggauss(nlat)
    return np.arccos(nodes[::-1])


def scalar_harmonic_surface(
    nlat: int = 89,
    nlon: int = 180,
    degree: int = 12,
    order: int = 6,
    amplitude: float = 0.22,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Build a closed spherical-harmonic radius surface on a Gauss grid."""
    colat = gaussian_colatitudes(nlat)
    lon = np.linspace(0.0, 2.0 * np.pi, nlon + 1)
    theta2d, lon2d = np.meshgrid(colat, lon, indexing="ij")

    field = np.real(sph_harm_y(degree, order, theta2d, lon2d))
    field /= np.max(np.abs(field))
    radius = 1.0 + amplitude * field

    x = radius * np.sin(theta2d) * np.cos(lon2d)
    y = radius * np.sin(theta2d) * np.sin(lon2d)
    z = radius * np.cos(theta2d)
    return x, y, z, field


def render(
    output: Path,
    nlat: int = 89,
    nlon: int = 180,
    degree: int = 12,
    order: int = 6,
    amplitude: float = 0.22,
) -> None:
    x, y, z, field = scalar_harmonic_surface(nlat, nlon, degree, order, amplitude)

    norm = Normalize(vmin=-1.0, vmax=1.0)
    base_colors = cm.viridis(norm(field))
    shaded = LightSource(azdeg=315, altdeg=35).shade_rgb(base_colors[..., :3], z)
    facecolors = np.dstack([shaded, np.full_like(field, 1.0)])

    fig = plt.figure(figsize=(7, 7), dpi=120)
    ax = fig.add_subplot(projection="3d")
    ax.plot_surface(
        x,
        y,
        z,
        facecolors=facecolors,
        rstride=1,
        cstride=1,
        linewidth=0.08,
        edgecolor=(0.05, 0.18, 0.22, 0.13),
        antialiased=True,
        shade=False,
    )
    ax.set_box_aspect((1, 1, 1))
    ax.set_axis_off()
    ax.view_init(elev=22, azim=-58)
    ax.set_proj_type("persp", focal_length=0.85)
    ax.set_xlim(-1.22, 1.22)
    ax.set_ylim(-1.22, 1.22)
    ax.set_zlim(-1.22, 1.22)
    fig.subplots_adjust(left=0, right=1, bottom=0, top=1)

    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, transparent=True, bbox_inches = "tight")
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("readme/spherepack_docs_style.png"),
        help="PNG path to write.",
    )
    parser.add_argument("--nlat", type=int, default=89)
    parser.add_argument("--nlon", type=int, default=180)
    parser.add_argument("--degree", type=int, default=12)
    parser.add_argument("--order", type=int, default=6)
    parser.add_argument("--amplitude", type=float, default=0.22)
    args = parser.parse_args()

    render(
        output=args.output,
        nlat=args.nlat,
        nlon=args.nlon,
        degree=args.degree,
        order=args.order,
        amplitude=args.amplitude,
    )


if __name__ == "__main__":
    main()
